[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    --tb=short
    --cov=config
    --cov=leagues
    --cov=espn
    --cov=engine
    --cov-report=term-missing
    --cov-report=html
